# Theme metadata 
name = "monokai"

# Is theme light or dark?
light = false

# Primary
primary = "#A6E22D"

# Menu
menu_primary = "#272822"
menu_text = "#575b61"
menu_text_active = "#66d9ef"
menu_title = "#E8E8E3"                                                                               

# Backgrounds
background = "#2D2E27"
home_section_odd = "#3f4145"
home_section_even = "#575b61"

font = "rose"
